### ISSUE TITLE
Vina-GPU-2.0 - Linux compilation

### ISSUE THREAD

**Issue by rfleiro** [DeltaGroupNJUPT/Vina-GPU-2.0#2]
Hi, I am trying to compile vina-GPU-2 in Linux and am running into several issues that I need help fixing completely. Before I waste any more of your time and mine, **is the code ready for compilation in a Linux system? If not, is this on the roadmap?**

Thanks very much in advance!

Rafa

**Comment by dinghezier** [comment]
Hi, Please tell me which docking software is the vina-GPU-2 you are talking about, for example, Vina-GPU+, QuivkVina 2-GPU, QuickVina-W-GPU. And please tell me more details of the problems you encountered. Thank you.

**Comment by rfleiro** [comment]
Hi, I am trying to compile Vina-GPU+ on Ubuntu.22.04

I have:
1- Copied the makefile from Vina-GPU
2- Added "-std=c++17" to fix some initial errors.
3- Error now is:
`./OpenCL/src/wrapcl.cpp: In function ‘_cl_program* SetupBuildProgramWithBinary(cl_context, _cl_device_id**, const char*)’:
./OpenCL/src/wrapcl.cpp:422:10: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  422 |     fread(binary_buffer, sizeof(char), program_size, program_handle);
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`
4- Adding -Wno-unused-result hides the message but doesn't solve the original issue I guess. Make finishes and generates a Vina-GPU2 executable, but when I run it I get problems finding libraries:
`./Vina-GPU2: error while loading shared libraries: libboost_program_options.so.1.80.0: cannot open shared object file: No such file or directory
`
*When compiling Vina-GPU with the current setup, same boost installation, etc., everything works fine.

Many thanks for developing this and for the help :)

**Comment by dinghezier** [comment]
We have updated the linux version of Vina-GPU+, you can follow the steps we have provided to recompile it. And please avoid use _-OPENCL_1_2_ in the Makefile setting.

**Comment by rfleiro** [comment]
Thanks, managed to compile it now. I also had a mismatch between Nvidia driver and toolkit installed (11.8 vs 12.0), which made it crash too. I am leaving the comment here just in case someone runs into similar problem.

PS. Makefile still marks output as Vina-GPU instead of Vina-GPU+, maybe worth modify that or the README notes to make them match.

Thanks!

**Comment by dinghezier** [comment]
Hi, thank you for your advice, we will  modify it later
