### ISSUE TITLE
Error: could not open "./2bm2_receptor.pdbqt" for reading.

### ISSUE THREAD

**Issue by xavierchee** [DeltaGroupNJUPT/Vina-GPU-2.0#32]
I moved the protein and ligand to the main directory. 
So if i check the directory list, i get the following: 

2bm2_ligand.pdbqt   Makefile   Vina-GPU+.exe       main
2bm2_protein.pdbqt  OpenCL     Vina-GPU+_K.exe     test
Kernel1_Opt.bin     README.md  input_file_example  test_out
Kernel2_Opt.bin     Vina-GPU   lib

However, when i try to run
`./Vina-GPU --receptor ./2bm2_receptor.pdbqt --ligand ./2bm2_ligand.pdbqt --thread 8000 --center_x 40.415 --center_y 110.986 --center_z 82.673 --size_x 30 --size_y 30 --size_z 30`

I get the error:

Error: could not open "./2bm2_receptor.pdbqt" for reading.

Thanks!

**Comment by Glinttsd** [comment]
Hi, I think you should use `--receptor ./2bm2_protein.pdbqt` instead of `--receptor ./2bm2_receptor.pdbqt`
