### ISSUE TITLE
Error when running the program outside the installed program folder

### ISSUE THREAD

**Issue by pnakliang** [DeltaGroupNJUPT/Vina-GPU-2.0#5]
Hi, I have a question regarding the job submission and running the vina- gpu+,
After installation I already run the example as show in the instruction.it was successful. However, I run the job in different directory, I got an error. It said something like “ ./OpenGL/…. Cannot be found” (sorry I cannot remember it exactly, and will update it asap). So, I tried running the job like the example by creating the subfolder within the program directory and submitted the job like this 
./Vina-GPU —config ./input_file/config.txt

It turned out successfully. 
Anyone got the same issue? How to solve it? Or I have to run my jobs inside this folder only?

FYI. I’m using a Linux version on Ubuntu.
.

**Comment by rfleiro** [comment]
Hi, you need to include the Kernel files in the directory, either make symlinks or copy them before running the program

**Comment by pnakliang** [comment]
Thank you for the solution. I will try
