### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by guanwg** [DeltaGroupNJUPT/Vina-GPU-2.0#6]
[guanw@gra974 Vina-GPU+]$ ./Vina-GPU --config ./input_file_example/2bm2_config.txt
#################################################################
# If you used Vina-GPU in your work, please cite:               #
#                                                               #
#Shidi, Tang, Chen Ruiqi, Lin Mengru, Lin Qingde,               #
#Zhu Yanxiang, Wu Jiansheng, Hu Haifeng, and Ling Ming.         #
#Accelerating AutoDock VINA with GPUs. ChemRxiv (2021).Print.   #
#                                                               #
#DOI 10.26434/chemrxiv-2021-3qvn2-v3                            #
#                                                               #
# And also the origin AutoDock Vina paper:                      #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, Journal of Computational Chemistry 31 (2010)  #
# 455-461                                                       #
#                                                               #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
#################################################################

Using virtual sreening mode

Output will be in the directory ./test_out
Reading input ... done.
Setting up the scoring function ... done.
Using heuristic search_depth
Analyzing the binding site ... done.
GPU Platform: NVIDIA CUDAGPU Platform 1 version: OpenCL 3.0 CUDA 11.7.102

GPU Device: Tesla P100-PCIE-12GBPlatform 1 global memory size:12.790989 GB
Platform 1 local memory size:49.152000 KB

Using random seed: -2037035914
Err-9999:Unknown OpenCL error

**Comment by guanwg** [comment]
Running on NVIDIA P100 card.

I've edited the Makefile and Made the following changes:

1. Remove "thread.cpp" and "once.cpp" from compiling
2. Add -lboost_thread

**Comment by guanwg** [comment]
I've resolved the issue.

**Comment by ljnoit** [comment]
> I've resolved the issue.

Hello, 
Could you please tell me how to solve the problem?
I have the same problem.

```
Err-9999:Unknown OpenCL error
```
